### ISSUE TITLE
How to suppress log warnings?

### ISSUE THREAD

**Issue by ceteri** [digital-science/dimcli#54]
When using this library to access Dimensions API, every call outputs:

```
DimCli v0.6.1.2 - Succesfully connected to <https://app.dimensions.ai> (method: manual login)
```

Is there any config setting to suppress those?

It's quite annoying, not an especially "pythonic" practice, and makes integration with production code more difficult to manage than it needs to be.

Many thanks -

**Comment by lambdamusic** [comment]
That's a good point / we'll add a `verbose=False` option to the `login` method in next release so that you can suppress that. 

PS it was originally developed thinking of jupyter notebooks settings where users can benefit from a visual feedback..

**Comment by lambdamusic** [comment]
That's now in dimcli v0.6.2 - just do `login(verbose=False)`
See https://github.com/digital-science/dimcli/blob/master/dimcli/__init__.py#L31

**Comment by ceteri** [comment]
Thank you so much @lambdamusic !
