### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by giswqs** [digital-science/dimcli#74]
Any plan to add the package to conda-forge? I can't add dimcli as a package dependency until it is available on conda-forge.
https://github.com/conda-forge

**Comment by lambdamusic** [comment]
Hi, I'm not familiar with conda-forge, how would that work?

**Comment by giswqs** [comment]
Conda-forge is a community-led collection of recipes, build infrastructure, and distributions for the conda package manager. Package available on conda-forge can be installed using `conda install pkg-name -c conda-forge`. Almost all the popular Python packages available on PyPI are also available on conda-forge. You can check https://anaconda.org/conda-forge/repo for the tens of thousands of Python packages. Check the link [here](https://github.com/conda-forge/staged-recipes#getting-started) for instructions on how to submit a package to conda-forge.  I also have a video tutorial [here](https://youtu.be/NNWhz7pqwCw) showing step-by-step how to do it.

**Comment by sugatoray** [comment]
@giswqs I just added dimcli to conda-forge. (PR: https://github.com/conda-forge/staged-recipes/pull/17275)

![image](https://user-images.githubusercontent.com/10201242/146642394-18402e12-a8a1-4447-8fa2-43afd3abc8df.png)

**Comment by sugatoray** [comment]
@lambdamusic Since, now `dimcli` is directly available on conda-forge, it can be installed with:

```sh
conda install -c conda-forge dimcli
```

And docs should be updated. [(Installation)](https://digital-science.github.io/dimcli/getting-started.html#installation)

![image](https://user-images.githubusercontent.com/10201242/146642517-063c77e9-48d6-418f-bf94-2f235bcfa231.png)

**Comment by giswqs** [comment]
@sugatoray That's great. Thanks. 

I saw you use a workaround for [requirements.txt](https://github.com/digital-science/dimcli/blob/master/requirements.txt). This file should also be included in the the PyPI source distribution as I mentioned in https://github.com/digital-science/dimcli/issues/75. It needs to be fixed by the dimcli developers.

**Comment by sugatoray** [comment]
@lambdamusic I would request you to add the following to the repository readme, if possible.

## Installation

**with pip**

```sh
pip install dimcli -U
```

**with conda**

```sh
conda install -c conda-forge dimcli
```

**Comment by sugatoray** [comment]
@giswqs 

> It needs to be fixed by the dimcli developers.

Completely agree with you on this. The workaround is to get the library up into conda-forge. But so far python packaging is concerned, `requirements.txt` must be included in the source. And this needs to happen upstream (here by the devs/maintainers of dimcli).

**Comment by sugatoray** [comment]
The reason they need to include the `requirements.txt` (*reqflie*) file in the source (on PyPI) is as you see below. They are dynamically fetching the contents of the *reqfile* and then preparing a list of requirements (`REQUIREMENTS_DATA`), followed by finally feeding it to `setup.py:install_requires` on line `61`.

https://github.com/digital-science/dimcli/blob/36382e2933ece95baa02220f119da31c03f455f9/setup.py#L36-L44

https://github.com/digital-science/dimcli/blob/36382e2933ece95baa02220f119da31c03f455f9/setup.py#L58-L63

**Comment by lambdamusic** [comment]
Documentation updated: https://digital-science.github.io/dimcli/getting-started.html#installation

Thanks to both for the help! I'll look at the `requirements.txt` issue later..
