### ISSUE TITLE
Can't install dimcli from source

### ISSUE THREAD

**Issue by giswqs** [digital-science/dimcli#75]
The package source file [dimcli-0.9.5.tar.gz](https://files.pythonhosted.org/packages/fb/d4/4af2b47449317a658b5ea7ecfa261a72a439a4cf4eeee52f9bc44eeff084/dimcli-0.9.5.tar.gz) does not include [requirements.txt](https://github.com/digital-science/dimcli/blob/master/requirements.txt). As a result, pip install from source fails.  

![image](https://user-images.githubusercontent.com/5016453/145607217-7b44cfe1-eba8-48ee-a6eb-d43b8b168d07.png)

**Comment by lambdamusic** [comment]
Should be fixed with https://github.com/digital-science/dimcli/releases/tag/v0.9.6

**Comment by giswqs** [comment]
Great. Thanks.
