### ISSUE TITLE
Skip changes limit if I want to start extraction from hits over 50k

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [digital-science/dimcli#79]
When I use the iterative query to look up results starting over 50k which is the API limit, the iterative query function rewrites the hard-coded limit value. Thus, it is not possible to start the iteration over the API limit. I suspect the following code chunk is responsible for the behavior:

`
        MAXLIMIT = maxlimit or 50000
        flag_last_round = False
        if skip + limit >= MAXLIMIT:
            flag_last_round = True
            if skip + limit > MAXLIMIT:
                limit = MAXLIMIT - skip
`

**Comment by lambdamusic** [comment]
The Analytics API has a built-in upper limit of [50k records](https://docs.dimensions.ai/dsl/usagepolicy.html#technical-limits) for all queries. 

So in `dimcli` auto-iteration utility this is enforced, to avoid triggering an API error. 

You can test it out via a simple query, by setting the `skip` parameter at 50k: 

<img width="889" alt="image" src="https://github.com/digital-science/dimcli/assets/3493663/a42e09de-ca8a-4018-b1fb-f13f14d7b04b">
