### ISSUE TITLE
CLI: query history is backwards

### ISSUE THREAD

**Issue by k2d222** [digital-science/dimcli#80]
In the CLI, the query history is reversed. Pressing the up-arrow key (or ctrl+p) should show the most recent query. Instead, it shows the oldest.

dimcli version = 1.2 (Windows)

**Comment by lambdamusic** [comment]
Can't reproduce it, but maybe [this SO thread](https://stackoverflow.com/questions/62802667/print-python-history-from-interactive-prompt-on-windows) is relevant?

PS The built-in history is a little buggy anyways, we may consider removing it or replacing it with [in-memory history](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#history)
